module Depslist
  class Cli
    def version: -> void
    def list: (path: String?) -> void
    def server: -> void
  end

  class Handler
    def list: (String) -> Array[{
          "groupId" => String,
          "artifactId" => String,
          "version" => String,
        }]
  end
end
